Personal Project or Capstone/PortfolioWebsite/AppLabs/AppLabs.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppLabs.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Simple()
        {
            ViewBag.Message = "Simple C# and web application exercises";

            return View();
        }

        public ActionResult Moderate()
        {
            ViewBag.Message = "Moderate to difficult C# and web application exercises";

            return View();
        }

        public ActionResult Complex()
        {
            ViewBag.Message = "Complex C# and web applications, including mastery projects";

            return View();
        }


        public ActionResult About()
        {
            ViewBag.Message = "Complex C# and web applications, including mastery projects";

            return View();
        }


    }
}

Personal Project or Capstone/PortfolioWebsite/AppLabs/AppLabs.UI/Controllers/ModerateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppLabs.BLL.Level3;
using AppLabs.BLL.Level4;
using AppLabs.BLL.Level5;
using AppLabs.DTOs.Level3;
using AppLabs.DTOs.Level4;
using AppLabs.DTOs.Level5;
using AppLabs.UI.Models;

namespace AppLabs.UI.Controllers
{
    public class ModerateController : Controller
    {
        //
        // GET: /Moderate/
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult WordCounterInput()
        {
            var model = new WordCounterModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult WordCounterInput(WordCounterModel request)
        {
            if (ModelState.IsValid)
            {
                var wordFinder = new WordCounter();
                var wordData = new WordCounterRequest();
                wordData.UserInput = request.UserInput;
                

                var result = wordFinder.CountWords(wordData);
                return View("WordCounterOutput", result);

            }
            else
            {
                return View(request);
            }
        }


        public ActionResult CommonDenominatorInput()
        {
            var model = new CommonDenominatorModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult CommonDenominatorInput(CommonDenominatorModel request)
        {
            if (ModelState.IsValid)
            {
                var gcdFinder = new CommonDenominatorFinder();
                var gcdData = new CommonDenominatorRequest();
                gcdData.UserNumerator1 = request.UserNumerator1;
                gcdData.UserDenominator1 = request.UserDenominator1;
                gcdData.UserNumerator2 = request.UserNumerator2;
                gcdData.UserDenominator2 = request.UserDenominator2;


                var result = gcdFinder.FindDenominator(gcdData);
                return View("CommonDenominatorOutput", result);

            }
            else
            {
                return View(request);
            }
        }



        public ActionResult RomanNumeralInput()
        {
            var model = new RomanNumeralModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult RomanNumeralInput(RomanNumeralModel request)
        {
            if (ModelState.IsValid)
            {
                var romanConverter = new RomanNumeralConverter();
                var romanData = new RomanNumeralRequest();
                romanData.UserNumber = request.UserNumber;
                
                var result = romanConverter.ConvertNumber(romanData);
                return View("RomanNumeralOutput", result);

            }
            else
            {
                return View(request);
            }
        }



        public ActionResult MorseCodeInput()
        {
            var model = new MorseCodeModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult MorseCodeInput(MorseCodeModel request)
        {
            if (ModelState.IsValid)
            {
                var morseConverter = new MorseCodeConverter();
                var morseData = new MorseCodeRequest();
                morseData.UserInput = request.UserInput;

                var result = morseConverter.ConvertToMorse(morseData);
                return View("MorseCodeOutput", result);

            }
            else
            {
                return View(request);
            }
        }



        public ActionResult CipherInput()
        {
            var model = new CipherModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult CipherInput(CipherModel request)
        {
            if (ModelState.IsValid)
            {
                var cipherConverter = new CipherConverter();
                var cipherData = new CipherRequest();
                cipherData.UserInput = request.UserInput;

                var result = cipherConverter.EncryptWord(cipherData);
                return View("CipherOutput", result);

            }
            else
            {
                return View(request);
            }
        }


	}
}

Personal Project or Capstone/PortfolioWebsite/AppLabs/AppLabs.UI/Controllers/SimpleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppLabs.BLL.Level1;
using AppLabs.BLL.Level2;
using AppLabs.DTOs.Level1;
using AppLabs.DTOs.Level2;
using AppLabs.UI.Models;
using Microsoft.Ajax.Utilities;


namespace AppLabs.UI.Controllers
{
    public class SimpleController : Controller
    {
        //
        // GET: /Simple/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FloorCalculatorInput()
        {
            var model = new FloorCalculatorModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult FloorCalculatorInput(FloorCalculatorModel request)
        {
            if (ModelState.IsValid)
            {
                var floorCalc = new FloorCalculator();
                var floorData = new FloorCalculatorRequest();
                floorData.Length = request.Length.Value;
                floorData.Width = request.Width.Value;
                floorData.UnitCost = request.UnitCost.Value;

                var result = floorCalc.CalculateFloorCost(floorData);
                return View("FloorCalculatorOutput", result);

            }
            else
            {
                return View(request);
            }
        }

        public ActionResult TipCalculatorInput()
        {
            var model = new TipCalculatorModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult TipCalculatorInput(TipCalculatorModel request)
        {
            if (ModelState.IsValid)
            {
                var tipCalc = new TipCalculator();
                var tipData = new TipCalculatorRequest();
                tipData.MealTotal = request.MealTotal.Value;
                tipData.TipPercent = request.TipPercent.Value;

                var result = tipCalc.CalculateTip(tipData);
                return View("TipCalculatorOutput", result);
            }
            else
            {
                return View(request);
            }
        }

        public ActionResult LeapYearInput()
        {
            var model = new LeapYearCalculatorModel();
            return View(model);

        }


        [HttpPost]
        public ActionResult LeapYearInput(LeapYearCalculatorModel request)
        {
            if (ModelState.IsValid)
            {
                var leapCalc = new LeapYearCalculator();
                var leapData = new LeapYearRequest();
                leapData.StartYear = request.StartYear.Value;
                leapData.EndYear = request.EndYear.Value;

                var result = leapCalc.FindLeapYear(leapData);
                return View("LeapYearOutput", result);
            }
            else
            {
                return View(request);
            }
        }

        public ActionResult StringReverserInput()
        {
            var model = new StringReverserModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult StringReverserInput(StringReverserModel request)
        {
            if (ModelState.IsValid)
            {
                var stringFind = new StringReverser();
                var stringData = new StringReverseRequest();
                stringData.String = request.String;
                

                var result = stringFind.FindReverseString(stringData);
                return View("StringReverserOutput", result);

            }
            else
            {
                return View(request);
            }
        }



        public ActionResult VowelCounterInput()
        {
            var model = new VowelCounterModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult VowelCounterInput(VowelCounterModel request)
        {
            if (ModelState.IsValid)
            {
                var vowelFind = new VowelCounterCalculator();
                var vowelData = new VowelCounterRequest();
                vowelData.Word = request.Word;


                var result = vowelFind.FindVowels(vowelData);
                return View("VowelCounterOutput", result);

            }
            else
            {
                return View(request);
            }
        }



        public ActionResult PalindromeInput()
        {
            var model = new PalidromeFinderModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult PalindromeInput(PalidromeFinderModel request)
        {
            if (ModelState.IsValid)
            {
                var palinFind = new PalindromeCalculator();
                var palinData = new PalindromFinderRequest();
                palinData.Word = request.Word;


                var result = palinFind.FindPalindrome(palinData);
                return View("PalindromeOutput", result);

            }
            else
            {
                return View(request);
            }
        }

        public ActionResult ChangeReturnInput()
        {
            var model = new ChangeReturnModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult ChangeReturnInput(ChangeReturnModel request)
        {
            if (ModelState.IsValid)
            {
                var changeFind = new ChangeReturnCalculator();
                var changeData = new ChangeReturnRequest();
                changeData.UserCash = request.UserCash;
                changeData.ItemCost = (decimal) (request.ItemCost);


                var result = changeFind.CalculateChange(changeData);
                return View("ChangeReturnOutput", result);

            }
            else
            {
                return View(request);
            }
        }


        public ActionResult FibonacciInput()
        {
            var model = new FibonacciModel();
            return View(model);

        }

        [HttpPost]
        public ActionResult FibonacciInput(FibonacciModel request)
        {
            if (ModelState.IsValid)
            {
                var fibCalc = new FibonacciCalculator();
                var fibData = new FibonacciListerRequest();
                fibData.givenNumber = request.givenNumber;
                

                var result = fibCalc.FibonacciLister(fibData);
                return View("FibonacciOutput", result);

            }
            else
            {
                return View(request);
            }
        }





    }
}

Personal Project or Capstone/PortfolioWebsite/AppLabs/AppLabs.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body id="top">
    <div id="cv">
        <div class="mainDetails">
            <div id="headshot">
                <img src="../../Images/photo%20(1).JPG" alt="" />
            </div>

            <div id="name">
                <h1>Seetal Patel</h1>
                <h2>Junior Developer</h2>
            </div>

            <div id="contactDetails">
                <ul>
                    <li><b>Email: </b>patel [dot] seetal [at] gmail [dot] com</li>
                    <li><b>Skype: </b>seetalp</li>
                    <li><b><a href="https://www.linkedin.com/pub/seetal-patel/30/671/9b1">LinkedIn</a></b></li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>

        <div id="mainArea">
            <section>
                <article>
                    <div class="sectionTitle">
                        <h1>Profile</h1>
                    </div>

                    <div class="sectionContent">
                        <p style="font-style:italic;"> I have more than seven years of professional experience with HR systems in both the federal government and private sector, with a strong focus on workforce metrics and real-time analytical solutions. A growing interest in the technical side of these systems led me to the Software Craftsmanship Guild, where I am currently participating in an intensive software developer apprenticeship to gain skills in full-stack development. I hope to use this experience to pivot into a career in database and/or application development, particularly one that dovetails with my interests in data modeling and management, analytics and user experience.</p>
                    </div>
                </article>
                <div class="clear"></div>
            </section>
            
            <section>
                <div class="sectionTitle">
                    <h1>Key Skills</h1>
                </div>

                <div class="sectionContent">
                    
                        <ul class="keySkills">
                            <li>C#/.NET Framework</li>
                            <li>Unit Testing (Nunit)</li>
                            <li>ASP.NET MVC 5</li>
                            <li>SQL Server/TSQL</li>
                            <li>SSMS/SSRS/SSIS</li>
                            <li>ADO.NET</li>
                            <li>HTML5/CSS</li>
                            <li>Javascript/JQuery</li>
                            <li>Entity Framework</li>
                        </ul>
                    
                </div>
                <div class="clear"></div>
            </section>

            <section>
                <div class="sectionTitle">
                    <h1>Work Experience</h1>
                </div>

                <div class="sectionContent" style="padding-bottom: 20px;">
                    <article>
                        <h2><b>Associate Director, Data and Operations</b></h2>
                        <p class="subDetails">The Advisory Board Company</p>
                        <p class="subDetails">2012-2014</p>
                         </article>

                    <article>
                        <h2><b>Management Analyst, Human Resources</b></h2>
                        <p class="subDetails">Federal Energy Regulatory Commission</p>
                        <p class="subDetails">2009-2012</p>
                          </article>

                    <article>
                        <h2><b>Research Specialist, Organizational Learning & Effectiveness</b></h2>
                        <p class="subDetails">Center for Naval Analysis</p>
                        <p class="subDetails">2009</p>
                         </article>
                    
                    <article>
                        <h2><b>Workforce Analyst, Workforce Services</b></h2>
                        <p class="subDetails">Washington Metropolitan Area Transit Authority</p>
                        <p class="subDetails">2007-2009</p>
                    </article>
                </div>
                <div class="clear"></div>
            </section>



            <section>
                <div class="sectionTitle">
                    <h1>Education</h1>
                </div>

                <div class="sectionContent" style="padding-bottom: 20px;">
                    <article>
                        <h2><b>University of Illinois at Urbana–Champaign</b></h2>
                        <p class="subDetails">Masters in Human Resources and Industrial Relations</p>
                    </article>

                    <article>
                        <h2><b>University of Wisconsin at Madison</b></h2>
                        <p class="subDetails">Bachelors of Science in Psychology</p>
                    </article>
                </div>
                <div class="clear">
                    
                </div>
            </section>

        </div>
    </div>

</body>

Personal Project or Capstone/PortfolioWebsite/AppLabs/AppLabs.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contact</h2>

Personal Project or Capstone/PortfolioWebsite/AppLabs/AppLabs.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

    <div class="row" id="toprow">
        <div class="col-md-2">
           <img src="../../Images/SPlogo.png" alt="" />
        </div>
        <div class="col-md-10">
            <h2>Seetal Patel</h2>
            <h3>C#/.NET Developer Portfolio</h3>
            <p class="lead">This site provides examples of my programming work using C#, ASP.NET MVC 5, HTML, CSS and JavaScript.</p>
        </div>
    </div>


<div class="row">
    <div class="col-md-4">
        <h3>Basic Exercises in C#</h3>
        <p>Simple applications using ASP.NET/C# and the NUnit framework</p>
        <p><button id="button1" type="button" class="btn btn-default"><b>@Html.ActionLink("More", "Index", "Simple")</b></button></p> 
    </div>
    <div class="col-md-4">
        <h3>Intermediate Exercises in C#</h3>
        <p>Advanced exercises using ASP.NET/C# and the NUnit framework </p>
        <p><button id="button1" type="button" class="btn btn-default"><b>@Html.ActionLink("More", "Index", "Moderate")</b></button></p>
    </div>
    <div class="col-md-4">
        <h3>Full Applications</h3>
        <p>Coming soon!</p>
        <p><button id="button1" type="button" class="btn btn-default"><b>@Html.ActionLink("More", "Index", "Home")</b></button></p>
    </div>
</div>