Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Models/AddDVDRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using DVDLibrary.DTOs;

namespace DVDLibrary.Web.Models
{
    public class AddDVDRequest
    {


        [Required(ErrorMessage = "Please enter a movie title!")]
        public string Title { get; set; }
        public string Rating { get; set; }
        [Required(ErrorMessage = "Please enter a year that is after 1900 and before 2020!")]
        [Range(1900,2020)]
        public int Year { get; set; }
        [Required(ErrorMessage = "Please enter a valid runtime")]
        [Range(0, 1000)]
        public int Runtime { get; set; }
        public string Director { get; set; }
        public string Star { get; set; }
                


        public DVD CreateDVD()
        {
            return new DVD
            {
                Title = Title,
                Rating = Rating,
                Year = Year,
                Runtime = Runtime,
                Director = Director,
                Star = Star
            };
        }



    }
}

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Models/EditDVDRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using DVDLibrary.DTOs;

namespace DVDLibrary.Web.Models
{
    public class EditDVDRequest
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter a title!")]
        public string Title { get; set; }
        public string Rating { get; set; }
        [Required(ErrorMessage = "Please enter a year that is after 1900 and before 2020!")]
        [Range(1900, 2020)]
        public int Year { get; set; }
        [Required(ErrorMessage = "Please enter a valid runtime")]
        [Range(0, 1000)]
        public int Runtime { get; set; }
        public string Director { get; set; }
        public string Star { get; set; }

        public EditDVDRequest()
        {
            
        }

        public EditDVDRequest(DVD dvd)
        {
            Id = dvd.Id;
            Title = dvd.Title;
            Rating = dvd.Rating;
            Year = dvd.Year;
            Runtime = dvd.Runtime;
            Director = dvd.Director;
            Star = dvd.Star;
        }

        public DVD CreateDvd()
        {
            return new DVD
            {
                Id = Id,
                Title = Title,
                Rating = Rating,
                Year = Year,
                Runtime = Runtime,
                Director = Director,
                Star = Star
            };
        }
    }
}

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Models/MovieDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DVDLibrary.DTOs;

namespace DVDLibrary.Web.Models
{
    public class MovieDetails
    {
        public DVD Movie { get; set; }
    }

    
}

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Models/SearchDVDRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using DVDLibrary.DTOs;

namespace DVDLibrary.Web.Models
{
    public class SearchDVDRequest
    {
        
        public string SearchTitle { get; set; }
        public string SearchDirector { get; set; }
        public string SearchActor { get; set; }


        public List<DVD> SearchResults { get; set; }


        //public SearchDVDRequest()
        //{
        //    SearchResults = new List<DVD>();
        //}
       

    }
}

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Controllers/DVDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using DVDLibrary.DTOs;
using DVDLibrary.DTOs.Interfaces;
using DVDLibrary.Web.Models;


namespace DVDLibrary.Web.Controllers
{
    public class DVDController : Controller
    {

        private readonly IDVDRepository _repository;

        public DVDController(IDVDRepository repository)
        {
            _repository = repository;
        }


        public ActionResult Add()
        {
            var model = new AddDVDRequest();
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(AddDVDRequest model)
        {
            if (ModelState.IsValid)
            {
                _repository.Add(model.CreateDVD());
                TempData["Message"] = "You just added a new DVD to your library!";
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }


        public ActionResult Edit(int id)
        {
            var dvd = _repository.GetbyID(id);
            var model = new EditDVDRequest(dvd);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditDVDRequest model)
        {
            if (ModelState.IsValid)
            {
                _repository.Edit(model.CreateDvd());
                TempData["Message"] = "DVD details have been changed!";
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {

            _repository.Delete(id);
            TempData["Message"] = "The DVD has been deleted from your library!";
            return RedirectToAction("Index", "Home", new{id});
        }



        public ActionResult Details(int id)
        {
            var model = _repository.GetbyID(id);

            return View(model);
        }

    }
}

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DVDLibrary.Web.Models;
using DVDLibrary.DTOs.Interfaces;

namespace DVDLibrary.Web.Controllers
{
    public class HomeController : Controller
    {

        private readonly IDVDRepository _repository;


        public HomeController(IDVDRepository repository)
        {
            _repository = repository;
        }

        //
        // GET: /Home/
        public ActionResult Index()
        {
            var model = new SearchDVDRequest();//You need to instantiate in the home controller since your search function is on your home index page
            model.SearchResults= _repository.GetAllDvds();
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(SearchDVDRequest model)
        {
            if (string.IsNullOrWhiteSpace(model.SearchActor) && string.IsNullOrWhiteSpace(model.SearchTitle) &&
                string.IsNullOrWhiteSpace(model.SearchDirector))
            {
                ModelState.AddModelError("", "You must fill in at least one search field");
                model.SearchResults = _repository.GetAllDvds();

                return View(model);
            }

            model.SearchResults = _repository.Search(model.SearchDirector, model.SearchTitle, model.SearchActor);

            return View(model);
        }

	}
}

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Views/DVD/Add.cshtml
@model DVDLibrary.Web.Models.AddDVDRequest

@{
    ViewBag.Title = "Add";
}

<h2>Add a New Movie</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Rating, new[]
        {
            new SelectListItem(){Text="G", Value = "G"},
            new SelectListItem(){Text="PG", Value = "PG"},
            new SelectListItem(){Text="PG-13", Value = "PG-13"},
            new SelectListItem(){Text="NC-17", Value = "NC-17"},
            new SelectListItem(){Text="R", Value = "R"},
            new SelectListItem(){Text="X", Value = "X"},
        })
                @Html.ValidationMessageFor(model => model.Rating)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Runtime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Runtime) <p> minutes</p>
                @Html.ValidationMessageFor(model => model.Runtime)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Director, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director)
                @Html.ValidationMessageFor(model => model.Director)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Star, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Star)
                @Html.ValidationMessageFor(model => model.Star)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" /> @Html.ActionLink("Back to List", "Index", "Home")
            </div>
        </div>
    </div>
}

  

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Views/DVD/Details.cshtml
@using DVDLibrary.Web.Controllers
@model DVDLibrary.DTOs.DVD

@{
    ViewBag.Title = "Details";
}

<h2>Movie Details</h2>


<h4>@Html.DisplayFor(model => model.Rating)|@Html.DisplayFor(model => model.Runtime) minutes|@Html.DisplayFor(model => model.Year)</h4>

<div>
    <hr />
    <dl class="dl-horizontal">

        
        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Star)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.Star)
        </dd>

    </dl>


        <div class="form-actions no-color">

            @Html.ActionLink("Back to List", "Index", "Home")

        </div>

</div>

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Views/DVD/Edit.cshtml
@model DVDLibrary.Web.Models.EditDVDRequest

@{
    ViewBag.Title = "Edit";
}
<div class="row">
    <div class="col-sm-12">
        <table class="table-responsive">
            <tr>
                <td class="table-condensed">
                    <h2>Edit Movie</h2>
                </td>

                <td>
                
                    @using (Html.BeginForm("Delete", "DVD", new { id = Model.Id }, FormMethod.Post))
                    {
                        @Html.Hidden("ID", Model.Id)
                        <input id="deleteBtn" type="submit" value="Delete" class="btn btn-danger"/>
                        

                    }

                </td>
            </tr>
        </table>
    </div>
</div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true)
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title)
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Rating, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Rating, new[]
        {
            new SelectListItem(){Text="G", Value = "G"},
            new SelectListItem(){Text="PG", Value = "PG"},
            new SelectListItem(){Text="PG-13", Value = "PG-13"},
            new SelectListItem(){Text="NC-17", Value = "NC-17"},
            new SelectListItem(){Text="R", Value = "R"},
            new SelectListItem(){Text="X", Value = "X"},
        })
                    @Html.ValidationMessageFor(model => model.Rating)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Year, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Year)
                    @Html.ValidationMessageFor(model => model.Year)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Runtime, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Runtime) <p> minutes</p>
                    @Html.ValidationMessageFor(model => model.Runtime)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Director, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Director)
                    @Html.ValidationMessageFor(model => model.Director)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Star, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Star)
                    @Html.ValidationMessageFor(model => model.Star)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }


@section scripts
{
    <script>
        $(document).ready(function() {
            $("#deleteBtn").click(function (e) {
                if (!confirm('Are you sure you want to delete?'))
                    e.preventDefault();
            });
        });
    </script>
}

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Views/Home/Index.cshtml
@model DVDLibrary.Web.Models.SearchDVDRequest

@{
    ViewBag.Title = "Index";
}

<h2>DVD Collection</h2>

<h3>@Html.ActionLink("Add a DVD", "Add", "DVD")</h3>


<div class="row">
    <h4><b>Search</b></h4>
 
    <div class= "col-sm-12" >
        @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { role = "form", @class = "form-inline" }))
        {
            <table>
                <tr>
                    <td class ="table-bordered col">
                        <div class="form-group">
                            <label>Title</label>
                            @Html.TextBoxFor(m => m.SearchTitle)
                        </div>

                        <div class="form-group">
                            <label>Director</label>
                            @Html.TextBoxFor(m => m.SearchDirector)
                        </div>

                        <div class="form-group">
                            <label>Actor</label>
                            @Html.TextBoxFor(m => m.SearchActor)
                        </div>

                        <button type="submit" class="btn btn-default">Search</button>
                        @Html.ValidationSummary(true)

                    </td>
                </tr>

            </table>
        }
    </div>
</div>



@if (Model.SearchResults !=null)
{
    <div class="row topMargin">
        <div class="col-sm-12">
            
            @if(Model.SearchResults.Any())
            { 
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Director</th>
                        <th>Year</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var dvd in Model.SearchResults)
                    {
                        <tr>
                            <td>@dvd.Title</td>
                            <td>@dvd.Director</td>
                            <td>@dvd.Year</td>
                            <td>@Html.ActionLink("Edit", "Edit", "DVD", new { id = dvd.Id }, null) |@Html.ActionLink("Details", "Details", "DVD", new { id = dvd.Id }, null)  </td>
                        </tr>
                    }
                </tbody>
            </table>
            }
            else
            {
            <h4>You do not have any DVDs in your collection!</h4> 
            }
        </div>
    </div>

}

Basic and Intermediate Exercises/DVDLibrary/DVDLibrary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
  
<body>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>