Final Mastery Project/FamileLMS/FamileLMS.UI/Controllers/ParentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FamileLMS.Data;
using FamileLMS.Models.Requests;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using FamileLMS.Models;

namespace FamileLMS.UI.Controllers
{
    public class ParentController : Controller
    {
        private ParentRepository repository=new ParentRepository();


        public ActionResult Index()
        {
            var model = repository.GetStudents(User.Identity.GetUserId());
            
            return View(model);
        }
        private StudentRepository studentrepo=new StudentRepository();

        [HttpPost]
        public ActionResult ChildClasses(string UserID)
        {
            var model = studentrepo.GetListofClassesWithGrades(UserID);
            foreach (var item in model)
            {
                item.UserID = UserID;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Grades(ParentGradeRequest request)//compare to StudentController Grades
        {
            var model = repository.GetStudentAssignmentGradesbyClass(request.ChildID, request.ClassID);
            ViewBag.ClassID = request.ClassID;
            ViewBag.StudentID = request.ChildID; //must cast in View
            return View(model);
        }
	}

}

Final Mastery Project/FamileLMS/FamileLMS.UI/Views/Parent/ChildClasses.cshtml
@model List<FamileLMS.Models.Views.StudentDashboard>

@{
    ViewBag.Title = "ChildClasses";
}

<h2>Your child's classes:</h2>

<table class="table table-bordered">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ClassName</td>
                <td>@item.LetterGrade</td>
                <td>
                    @using (Html.BeginForm("Grades", "Parent", FormMethod.Post, new { role = "form" }))
                    {
                        @Html.Hidden("ClassID", item.ClassID);
                        @Html.Hidden("ChildID", item.UserID);
                        <input type="submit" value="View Grades" />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Final Mastery Project/FamileLMS/FamileLMS.UI/Views/Parent/Grades.cshtml
@model List<FamileLMS.Models.Views.StudentAndParentGrade>
@{
    ViewBag.Title = "Grades";
}

<h2>Grades</h2>
@using (Html.BeginForm("ChildClasses", "Parent", FormMethod.Post, new { role = "form" }))
{
    @Html.Hidden("UserID", (string)ViewBag.StudentID);
    <input type="submit" value="Return to classes" />
}

<div class="row">
    <div class="col-sm-12">
        <ul class="list-inline">
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
</div>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-2 assignment-box">
            <p><strong>@item.EntryName</strong></p>
            <p>@item.PercentGrade % -- @item.LetterGrade</p>
        </div>
    }
</div>

Final Mastery Project/FamileLMS/FamileLMS.UI/Views/Parent/Index.cshtml
@model List<FamileLMS.Models.Views.ParentDashboard>
@{
    ViewBag.Title = "Index";
}
<h2>Parent Dashboard</h2>
<br />
<div class="row">
    <div class="col-sm-12">
        <ul class="list-inline">
            <li>@Html.ActionLink("Home", "Index", "Home", new { id = ViewContext.RouteData.Values["id"] }, null)</li>
            <li>@Html.ActionLink("Dashboard", "Index", "Parent", new { id = ViewContext.RouteData.Values["id"] }, null)</li>
            <li>@Html.ActionLink("Account", "Manage", "Account", new { id = ViewContext.RouteData.Values["id"] }, null)</li>
        </ul>
    </div>
</div>
<br />
<h3>My Students</h3>
<table class="table table-striped">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FirstName @item.LastName</td>
                <td>
                    @using (Html.BeginForm("ChildClasses", "Parent", FormMethod.Post, new { role = "form" }))
                    {
                        @Html.Hidden("UserID", item.UserID);
                        <input type="submit" value="View Classes" />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>